name: Backend Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-backend:
    name: Test Backend (.NET)
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: |
        cd backend
        dotnet restore
        
    - name: Build
      run: |
        cd backend
        dotnet build --no-restore --configuration Release
        
    - name: Test
      run: |
        cd backend
        dotnet test --no-build --verbosity normal --configuration Release 